version: "3.9"
services:
  redis:
    image: redis:7
    ports: ["6379:6379"]
  pg:
    image: postgres:16
    environment:
      POSTGRES_USER: agentic
      POSTGRES_PASSWORD: agentic
      POSTGRES_DB: agentic
    ports: ["5432:5432"]
    volumes: [pgdata:/var/lib/postgresql/data]
  mcp:
    build:
      context: .
      dockerfile: Dockerfile.mcp
    environment:
      - MCP_BIND=0.0.0.0:7000
    ports: ["7000:7000"]
    depends_on: [redis, pg]
  gateway:
    build:
      context: .
      dockerfile: Dockerfile.api
    environment:
      - DB_URL=postgresql+psycopg://agentic:agentic@pg:5432/agentic
      - REDIS_URL=redis://redis:6379/0
      - MCP_HOST=mcp
      - MCP_PORT=7000
    ports: ["8080:8080"]
    depends_on: [redis, pg, mcp]
volumes:
  pgdata:
