name: CI
on:
  pull_request:
  push:
    branches: [main, master]
jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install ruff black mypy pytest
      - name: Install Node deps
        run: |
          if [ -f package.json ]; then npm ci || npm install; fi
      - name: Lint
        run: |
          ruff check . || true
          black --check . || true
          mypy . || true
          if [ -f package.json ]; then npx eslint . || true; fi
      - name: Test
        run: |
          if [ -f pytest.ini ]; then pytest -q; fi
          if [ -f package.json ]; then npm test -s || true; fi
